export const categories = [
  "Antiques",
  "Art",
  "Astrology & Metaphysical",
  "Automotive",
  "Baby",
  "Books",
  "Business & Industrial",
  "Cameras",
  "Cell Phones & Accessories",
  "Clothing, Shoes & Accessories",
  "Coins & Paper Money",
  "Collectables",
  "Computers/Tablets & Networking",
  "Consumer Electronics",
  "Crafts",
  "Dolls & Bears",
  "DVDs & Movies",
  "Entertainment Memorabilia",
  "Gift Cards & Coupons",
  "Health & Beauty",
  "Jewelry & Watches",
  "Miscellaneous",
  "Music",
  "Musical Instruments & Gear",
  "Pet Supplies",
  "Pottery & Glass",
  "Real Estate",
  "Sporting Goods",
  "Sports Memorabilia, Cards and Fan Shop",
  "Stamps",
  "Tickets & Experiences",
  "Toys & Hobbies",
  "Travel",
];
